spring:
  application:
    name: spring-cloud-eureka-feign-client
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9999/eureka}

